---
server:
  port: 10130
grpc:
  host: localhost
  port: 10131
  oeminfo:
    host: localhost
    port: 10161
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: debug
    
shellshellfish:
  user-login-url: "http://localhost:10070"
  userinfo-url: "http://localhost:10060"
  finance-url: "http://localhost:10120"
  asset-alloction-url: "http://localhost:10020"
  trade-order-url: "http://localhost:10100"
  trade-pay-url: "http://localhost:10110"
  data-manager-url: "http://localhost:10030"
  
security:
  basic:
    enabled: false

  