---
server:
  port: 10030
#  contextPath: /
---
spring:
  jpa:
    open-in-view: false
  data:
      mongodb:
        database: funds
        host: 192.168.1.10
        port: 27017
  http:
    multipart:
#      max-file-size: 2MB
#      max-request-size: 10MB
datasource:
#  sampleapp:
#    url: jdbc:mysql://192.168.1.10:3306/ssftrdorder?useUnicode=true&characterEncoding=utf-8
#    username: sa
#    password: abcd1234
#    driverClassName: com.mysql.jdbc.Driver
#    defaultSchema:
#    maxPoolSize: 20
#    hibernate:
#      hbm2ddl.method: update
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect
shellshellfish:
  asset-alloction-url: "http://localhost:10020"
  userinfo-url: "http://localhost:10060"

grpc:
  asset-allocation:
    host: localhost
    port: 10021

management:
  endpoints:
    web:
      base-path: /