---
server:
  port: 10170
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.springframework.data: info

---

spring:
  data:
    mongodb:
      database: ssfui
      host: 192.168.1.10
      port: 27017
      zhongzheng: "zhongzheng"
      funds: "funds"
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
     listener:
       simple:
         acknowledge-mode: auto
     username: ssf
     password: shellshellfish
     host: 192.168.1.249
     port: 5772
     virtual-host: aaas
  redis:
    host: 192.168.1.10
    port: 6379
    password: redis123
    timeout: 0
    pool:



grpc:
  port: 10171

