server:
  port: 10100
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: debug
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
    username: ssf
    password: shellshellfish
    host: external-rabbitmq-service
    port: 5672
    virtual-host: aaas
    topicQueuePayName: com-ssf-topic-queue-pay
    topicQueueOrderName: com-ssf-topic-queue-order
    topicExchangeName: com-ssf-topic-exchange
    topicPay: shellshellfish.pay
    topicOrder: shellshellfish.order
  data:
    mongodb:
      host: external-mongo-service
      port: 27017
      database: zhongzheng
  redis:
    host: redis-service
    port: 6379
    password: redis123
    timeout: -1ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
datasource:
  sampleapp:
    url: jdbc:mysql://external-mysql-service:3306/ssftrdorder?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8
    username: sa
    password: 1rIQ9wi!@g3P$Qh* 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssftrdorder
    maxPoolSize: 20
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL57Dialect
      id.new_generator_mappings: false


grpc:
  finance_prod_client:
    host: aaas-api-asset-allocation
    port: 10021
  pay_client:
    host: aaas-finance-trade-pay
    port: 10111
  order_server:
    host: aaas-finance-trade-order
    port: 10101
  datacollection_client:
    host: aaas-app-datacollection-server
    port: 10091
  userinfo_client:
    host: aaas-api-user-info
    port: 10061

management:
  endpoints:
    web:
      base-path: /