---
server:
  port: 10070
  contextPath: /

spring:
  profiles: test
datasource:
  sampleapp:
    url: jdbc:mysql://192.168.1.249:30006/ssflogin?useUnicode=true&characterEncoding=utf-8
    username: sa
    password: N4eTVr89lX9BaPcx
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
  host: localhost
  port: 10071
ali:
    accessKeyId: LTAIpZL9r6q0kkPV
    accessKeySecret: dBsex06RIIB7LfBF2Pdx4TeRzpklwr
app:
    debug: true
redis:
    host: localhost
    port: 6379
    pwd: redis123
sms:
    signcode: SMS_117526841
    signname: 财富E智投