version: "2"


services:
  aaas-api-finance:
    image: aaas-api-finance:latest
    labels:
      - "aaas-api-finance"
    ports:
      - "10120:10120"
      - "10121:10121"
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - _JAVA_OPTIONS=-Xmx256m
      - TZ=Asia/Shanghai
      
      
