server:
  port: 10020

mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      password: 1rIQ9wi!@g3P$Qh*
      url: jdbc:mysql://localhost:3306/choice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: ssf08
#        password: uCIPzdEJzbeoFAMj
#        url: jdbc:mysql://172.16.128.72:3306/choicecopy?useUnicode=true&characterEncoding=utf-8
#        username: ssf09
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: funds
      host: localhost
      port: 27017
      collection: portfolio_yield_all
grpc:
  host: localhost
  port: 10021
  daily-fund-client:
    host: localhost
    port: 10091

application:
    swagger:
        title: SSF Platform API
        description: Shell shell fish API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl: