server:
  port: 10020

mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 1rIQ9wi!@g3P$Qh*
        url: jdbc:mysql://external-mysql-service:3306/choice?useUnicode=true&characterEncoding=utf-8
        username: ssf08
    jpa:
      hibernate:
        ddl-auto: update
    data:
      mongodb:
        database: ssf_asset_allo
        host: 192.168.1.10
        port: 27017
        collection: portfolio_yield_all

datasource:
  sampleapp:
    url: jdbc:mysql://external-mysql-service:3306/choice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ssf08
    password: 1rIQ9wi!@g3P$Qh*
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssf08
    maxPoolSize: 20
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
#  host: localhost
  port: 10021
  daily-fund-client:
    host: aaas-funds-datacollection-server
    port: 10091

application:
    swagger:
        title: SSF Platform API
        description: Shell shell fish API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
